import {
  Network,
  Database,
  ShieldCheck,
  User,
  Users,
  ConciergeBell,
  ChefHat,
  Smartphone,
  Globe,
  Server,
  Gauge,
  TrendingDown,
  Wrench,
  Eye,
  Plus,
  Pencil,
  Trash2,
  MapPin,
  Bike,
  ReceiptText,
  RefreshCw,
  Table2,
  Search,
  Zap,
  Clock,
  Link2,
  Columns3,
  Rows3,
  Activity,
  BookOpen,
  TriangleAlert,
  Warehouse,
  UtensilsCrossed,
  Store,
  Boxes,
  Tag,
  BarChart3,
  Plane,
  Lock,
  LockOpen,
  Unlock,
  KeyRound,
  Fingerprint,
  Mail,
  Timer,
  Monitor,
  Chrome,
  ScanFace,
  Hourglass,
  BadgeCheck,
  Contact,
  Layers,
  Building2,
  GitMerge,
  Rocket,
  Bell,
  CreditCard,
  Split,
  Scale,
  Cpu,
  Workflow,
  RadioTower,
  Star,
  Flame,
  Filter,
  SlidersHorizontal,
  ArrowUpDown,
  Leaf,
  SpellCheck,
  Sparkles,
  ThumbsUp,
  ThumbsDown,
  SkipForward,
  Heart,
  Clapperboard,
  Music,
  Snowflake,
  Repeat,
  MousePointerClick,
  Coffee,
  House,
  ServerCrash,
  Wifi,
  MemoryStick,
  HardDrive,
  type LucideIcon,
} from "lucide-react";

/**
 * String-keyed icon registry. Data modules and Server Components reference
 * icons by name (a serializable string) so they can cross the
 * server → client boundary; client components resolve the component here.
 */
export const icons = {
  network: Network,
  database: Database,
  shield: ShieldCheck,
  user: User,
  users: Users,
  waiter: ConciergeBell,
  kitchen: ChefHat,
  phone: Smartphone,
  globe: Globe,
  server: Server,
  gauge: Gauge,
  trendingDown: TrendingDown,
  wrench: Wrench,
  eye: Eye,
  plus: Plus,
  pencil: Pencil,
  trash: Trash2,
  mapPin: MapPin,
  bike: Bike,
  receipt: ReceiptText,
  refresh: RefreshCw,
  table: Table2,
  search: Search,
  zap: Zap,
  clock: Clock,
  link: Link2,
  columns: Columns3,
  rows: Rows3,
  activity: Activity,
  bookOpen: BookOpen,
  alert: TriangleAlert,
  warehouse: Warehouse,
  utensils: UtensilsCrossed,
  store: Store,
  boxes: Boxes,
  tag: Tag,
  chart: BarChart3,
  plane: Plane,
  lock: Lock,
  lockOpen: LockOpen,
  unlock: Unlock,
  key: KeyRound,
  fingerprint: Fingerprint,
  mail: Mail,
  timer: Timer,
  monitor: Monitor,
  chrome: Chrome,
  faceId: ScanFace,
  hourglass: Hourglass,
  badge: BadgeCheck,
  passport: Contact,
  layers: Layers,
  building: Building2,
  gitMerge: GitMerge,
  rocket: Rocket,
  bell: Bell,
  card: CreditCard,
  split: Split,
  scale: Scale,
  cpu: Cpu,
  workflow: Workflow,
  radio: RadioTower,
  star: Star,
  flame: Flame,
  filter: Filter,
  sliders: SlidersHorizontal,
  sort: ArrowUpDown,
  leaf: Leaf,
  spellcheck: SpellCheck,
  sparkles: Sparkles,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  skip: SkipForward,
  heart: Heart,
  film: Clapperboard,
  music: Music,
  snowflake: Snowflake,
  loop: Repeat,
  click: MousePointerClick,
  coffee: Coffee,
  home: House,
  serverCrash: ServerCrash,
  wifi: Wifi,
  memory: MemoryStick,
  drive: HardDrive,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function getIcon(name: IconName): LucideIcon {
  return icons[name];
}
